package packet_translate_pool

import (
	neteaseProtocol "Eulogist/core/minecraft/protocol"
	standardProtocol "Eulogist/core/standard/protocol"
)

// ...
var StandardContainerIDToNetEaseContainerID = map[uint8]uint8{
	standardProtocol.ContainerAnvilInput:                      neteaseProtocol.ContainerAnvilInput,
	standardProtocol.ContainerAnvilMaterial:                   neteaseProtocol.ContainerAnvilMaterial,
	standardProtocol.ContainerAnvilResultPreview:              neteaseProtocol.ContainerAnvilResultPreview,
	standardProtocol.ContainerSmithingTableInput:              neteaseProtocol.ContainerSmithingTableInput,
	standardProtocol.ContainerSmithingTableMaterial:           neteaseProtocol.ContainerSmithingTableMaterial,
	standardProtocol.ContainerSmithingTableResultPreview:      neteaseProtocol.ContainerSmithingTableResultPreview,
	standardProtocol.ContainerArmor:                           neteaseProtocol.ContainerArmor,
	standardProtocol.ContainerLevelEntity:                     neteaseProtocol.ContainerLevelEntity,
	standardProtocol.ContainerBeaconPayment:                   neteaseProtocol.ContainerBeaconPayment,
	standardProtocol.ContainerBrewingStandInput:               neteaseProtocol.ContainerBrewingStandInput,
	standardProtocol.ContainerBrewingStandResult:              neteaseProtocol.ContainerBrewingStandResult,
	standardProtocol.ContainerBrewingStandFuel:                neteaseProtocol.ContainerBrewingStandFuel,
	standardProtocol.ContainerCombinedHotBarAndInventory:      neteaseProtocol.ContainerCombinedHotBarAndInventory,
	standardProtocol.ContainerCraftingInput:                   neteaseProtocol.ContainerCraftingInput,
	standardProtocol.ContainerCraftingOutputPreview:           neteaseProtocol.ContainerCraftingOutputPreview,
	standardProtocol.ContainerRecipeConstruction:              neteaseProtocol.ContainerRecipeConstruction,
	standardProtocol.ContainerRecipeNature:                    neteaseProtocol.ContainerRecipeNature,
	standardProtocol.ContainerRecipeItems:                     neteaseProtocol.ContainerRecipeItems,
	standardProtocol.ContainerRecipeSearch:                    neteaseProtocol.ContainerRecipeSearch,
	standardProtocol.ContainerRecipeSearchBar:                 neteaseProtocol.ContainerRecipeSearchBar,
	standardProtocol.ContainerRecipeEquipment:                 neteaseProtocol.ContainerRecipeEquipment,
	standardProtocol.ContainerRecipeBook:                      neteaseProtocol.ContainerRecipeBook,
	standardProtocol.ContainerEnchantingInput:                 neteaseProtocol.ContainerEnchantingInput,
	standardProtocol.ContainerEnchantingMaterial:              neteaseProtocol.ContainerEnchantingMaterial,
	standardProtocol.ContainerFurnaceFuel:                     neteaseProtocol.ContainerFurnaceFuel,
	standardProtocol.ContainerFurnaceIngredient:               neteaseProtocol.ContainerFurnaceIngredient,
	standardProtocol.ContainerFurnaceResult:                   neteaseProtocol.ContainerFurnaceResult,
	standardProtocol.ContainerHorseEquip:                      neteaseProtocol.ContainerHorseEquip,
	standardProtocol.ContainerHotBar:                          neteaseProtocol.ContainerHotBar,
	standardProtocol.ContainerInventory:                       neteaseProtocol.ContainerInventory,
	standardProtocol.ContainerShulkerBox:                      neteaseProtocol.ContainerShulkerBox,
	standardProtocol.ContainerTradeIngredientOne:              neteaseProtocol.ContainerTradeIngredientOne,
	standardProtocol.ContainerTradeIngredientTwo:              neteaseProtocol.ContainerTradeIngredientTwo,
	standardProtocol.ContainerTradeResultPreview:              neteaseProtocol.ContainerTradeResultPreview,
	standardProtocol.ContainerOffhand:                         neteaseProtocol.ContainerOffhand,
	standardProtocol.ContainerCompoundCreatorInput:            neteaseProtocol.ContainerCompoundCreatorInput,
	standardProtocol.ContainerCompoundCreatorOutputPreview:    neteaseProtocol.ContainerCompoundCreatorOutputPreview,
	standardProtocol.ContainerElementConstructorOutputPreview: neteaseProtocol.ContainerElementConstructorOutputPreview,
	standardProtocol.ContainerMaterialReducerInput:            neteaseProtocol.ContainerMaterialReducerInput,
	standardProtocol.ContainerMaterialReducerOutput:           neteaseProtocol.ContainerMaterialReducerOutput,
	standardProtocol.ContainerLabTableInput:                   neteaseProtocol.ContainerLabTableInput,
	standardProtocol.ContainerLoomInput:                       neteaseProtocol.ContainerLoomInput,
	standardProtocol.ContainerLoomDye:                         neteaseProtocol.ContainerLoomDye,
	standardProtocol.ContainerLoomMaterial:                    neteaseProtocol.ContainerLoomMaterial,
	standardProtocol.ContainerLoomResultPreview:               neteaseProtocol.ContainerLoomResultPreview,
	standardProtocol.ContainerBlastFurnaceIngredient:          neteaseProtocol.ContainerBlastFurnaceIngredient,
	standardProtocol.ContainerSmokerIngredient:                neteaseProtocol.ContainerSmokerIngredient,
	standardProtocol.ContainerTradeTwoIngredientOne:           neteaseProtocol.ContainerTradeTwoIngredientOne,
	standardProtocol.ContainerTradeTwoIngredientTwo:           neteaseProtocol.ContainerTradeTwoIngredientTwo,
	standardProtocol.ContainerTradeTwoResultPreview:           neteaseProtocol.ContainerTradeTwoResultPreview,
	standardProtocol.ContainerGrindstoneInput:                 neteaseProtocol.ContainerGrindstoneInput,
	standardProtocol.ContainerGrindstoneAdditional:            neteaseProtocol.ContainerGrindstoneAdditional,
	standardProtocol.ContainerGrindstoneResultPreview:         neteaseProtocol.ContainerGrindstoneResultPreview,
	standardProtocol.ContainerStonecutterInput:                neteaseProtocol.ContainerStonecutterInput,
	standardProtocol.ContainerStonecutterResultPreview:        neteaseProtocol.ContainerStonecutterResultPreview,
	standardProtocol.ContainerCartographyInput:                neteaseProtocol.ContainerCartographyInput,
	standardProtocol.ContainerCartographyAdditional:           neteaseProtocol.ContainerCartographyAdditional,
	standardProtocol.ContainerCartographyResultPreview:        neteaseProtocol.ContainerCartographyResultPreview,
	standardProtocol.ContainerBarrel:                          neteaseProtocol.ContainerBarrel,
	standardProtocol.ContainerCursor:                          neteaseProtocol.ContainerCursor,
	standardProtocol.ContainerCreatedOutput:                   neteaseProtocol.ContainerCreatedOutput,
	standardProtocol.ContainerSmithingTableTemplate:           neteaseProtocol.ContainerSmithingTableTemplate,
}

// ...
var NetEaseContainerIDStandardContainerID map[uint8]uint8
