name: Build binaries and Upload to Release

permissions:
  contents: write

on:
  push:
    

env:
  OUT_PUT_DIR: build/
  PROG_NAME: eulogist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: build
        run: make all

